### PR TITLE
LuaStudio (Mac OS version) development tool

### PR DESCRIPTION
**Pull request by codeservice**
Helps your make OpenGL graphics games and mobile apps on Mac and export them to other OS including iOS, Android, Win easily. It's codding tool, based on Lua/LuaJIT programming language.

NOTE: A similar PR may already be submitted! Please search among the Pull request before creating one.

### Types of Changes

**What types of changes does your PR introduce?** Put an x in all boxes that apply

- [x ] New addition to list
- [ ] Fixing bug in existing item in list
- [ ] Removing item from list
- [ ] Changing structure (organization) of list

### Proposed Changes

**Describe each of your changes here to communicate to the maintainers why we should accept this pull request.**

1. If you're adding something to the list, be sure to explain why it should be added.
1. If you're fixing a bug or resolving a feature request, be sure to link to that issue.

### PR Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.

- [ x] I have read the CONTRIBUTING guide
- [x ] I have explained why this PR is important
- [x ] I have added necessary documentation (if appropriate)

### Further Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by codeservice** [comment]
Excellent choice! Only ZeroBraneStudio does not support LuaStudio libraries. It is possible integrate these libraries with any plugin based popular IDE like Eclipse or IntlliJ IDEA. LuaStudio exporter project has all necessary steps to make this possible. 

Agree LuaStudo has simple and basic editor which was made without intention to be best, General idea make something simple to start using OpenGL libraries without tricky integration.

**Comment by alichtman** [comment]
Hmm, let's hold off on this until a collaborator that knows `Lua` can comment.

I don't know enough about this to make an educated decision.

@xcv58 @jaywcjlove

**Comment by xcv58** [comment]
I do know Lua a little bit. Will investigate these choices after work.

**Comment by xcv58** [comment]
I try both IDE. Seems not very excited. Especially that LuaStudio is not actively maintained: https://github.com/luaforge/lua-studio (I probably find wrong repo).

**Comment by jaywcjlove** [comment]
I did not study LUA and need more comments. 

@alichtman I agree with your handling.

**Comment by codeservice** [comment]
I think maybe more proper place for this project here: https://github.com/ellisonleao/magictools
I added it as game development tool: https://github.com/ellisonleao/magictools/commit/7e720b7654c12592987c2e10e9ae1a33cde4e2d9 
LuaStudio more related to cross-platform graphics programming, specifically to game development. Adding it as Mac game development tool could be confusing.

If you have any problems with app evaluation simply close this pull request.

**Comment by xcv58** [comment]
Thanks for your understanding @codeservice !

**Pull request closed without merging**
