### PR TITLE
Add my own code editor: BeagleEditor

### PR DESCRIPTION
**Pull request by ManiProjs**
NOTE: A similar PR may already be submitted! Please search among the Pull request before creating one.

### Types of Changes

**What types of changes does your PR introduce?** Put an x in all boxes that apply

- [x] New addition to list
- [ ] Fixing bug in existing item in list
- [ ] Removing item from list
- [ ] Changing structure (organization) of list

### Proposed Changes

**Describe each of your changes here to communicate to the maintainers why we should accept this pull request.**

I added my own code editor that I wrote it. It is called "BeagleEditor" and its available for Windows, Mac and Linux
It has some features such as syntax highlighting, plugins and...

### PR Checklist

- [x] I have read the CONTRIBUTING guide
- [x] I have explained why this PR is important
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by jaywcjlove** [comment]
@ManiProjs Based on the description, this appears to be a code editor, but no detailed information is provided. It is recommended to include screenshots of the editor in the README.md to showcase its features and interface more clearly.

**Comment by ManiProjs** [comment]
@jaywcjlove Can you explain more, please?

**Comment by ManiProjs** [comment]
I think you mean add some screenshots to application's README.md. Ok, I did it.

**Comment by jaywcjlove** [comment]
@ManiProjs I couldn’t tell that your BeagleEditor app is an editor.

**Comment by ManiProjs** [comment]
Can you explain more?
I added some screenshots to its README.md

**Comment by jaywcjlove** [comment]
@ManiProjs  I didn't notice your screenshot before, but I just took another look and found that the most attractive screenshot is at the bottom. Wouldn't this make your application seem less appealing? I suggest putting the most attractive screenshot at the top so that users can see it right away.

Regarding "only applicable to BeagleEditor and its specified terminal commands," does this mean that without BeagleEditor or the specified command line environment, these features or commands will not work?

Our repository is meant to be an awesome mac repo, and if your application might not run, I don't think it's awesome enough.

**Comment by ManiProjs** [comment]
It’s not awesome?! Of course it’s awesome. My app works. You didn’t test
it. Install with Homebrew:
brew install beaglesoftware/cask/beagleeditor

**Comment by ManiProjs** [comment]
This app works! You must test it on your own computer. Don't judge too quickly! Install it on your own computer

**Pull request closed without merging**
