### PR TITLE
Remove KeePassX

### PR DESCRIPTION
**Pull request by heldev**
### Types of Changes

**What types of changes does your PR introduce?** Put an x in all boxes that apply

- [ ] New addition to list
- [ ] Fixing bug in existing item in list
- [x] Removing item from list
- [ ] Changing structure (organization) of list

### Proposed Changes

**Describe each of your changes here to communicate to the maintainers why we should accept this pull request.**

The project is abandoned and there are other KeePass compatible alternatives (including the official one)

### PR Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.

- [x] I have read the CONTRIBUTING guide
- [x] I have explained why this PR is important
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by alichtman** [comment]
See #407

**Comment by heldev** [comment]
@alichtman As I know KeePassX is a fork of KeePass, which is as you sad "open source and well audited". My point was KeePassX is abandoned (the last release is almost 2 years ago, and there is no activity on [Github](https://github.com/keepassx/keepassx/graphs/contributors) ) and it's not that well maintained and audited considering that it was created to run on *nix when KeePass could not do that and now KeePass (since v 2) works everywhere.

> Originally KeePassX was called KeePass/L for Linux since it was a port of Windows password manager KeePass Password Safe. After KeePass/L became a cross-platform application the name was not appropriate anymore and therefore, on 22 March 2006 it has been changed.

 So it seem's like a good candidate for deletion. 
What do you think if we just replace it with KeePass, which is one of the most popular password managers and the only OSS among them?

**Comment by heldev** [comment]
Plus there is already another OSS KeePass-compatible manager on the list (MacPass) which is still under active development

**Comment by alichtman** [comment]
You're right. I wasn't up on my history and didn't check that thoroughly enough.

I agree with you that we should remove KeePassX and I think MacPass is a great substitute (and it's already on the list, so no extra work.)

**Pull request merged**
