### PR TITLE
Added Caffeine - A utility app

### PR DESCRIPTION
**Pull request by applecool**
A utility app which prevents the mac from going to sleep with a single click.

@jaywcjlove Please take a look 😃

### CODE REVIEW

**Comment by xcv58** [comment]
This is duplicated with https://github.com/jaywcjlove/awesome-mac/blob/master/README-en.md#system-related

**Comment by jaywcjlove** [comment]
Behind the filter free to stay on top. Do you think would be okay? @xcv58

**Comment by xcv58** [comment]
@jaywcjlove Sorry I don't understand what you said. Probably I'm not putting myself clearly. My point is that there are two Caffeine in this list.

**Comment by applecool** [comment]
Sorry about that! I didn't notice that Caffeine was already there. Apologies!

**Pull request merged**
