### PR TITLE
Added TeXstudio - An integrated environment for LaTeX

### PR DESCRIPTION
**Pull request by applecool**
@jaywcjlove Please take a look 😃

### CODE REVIEW

**Comment by applecool** [comment]
@jaywcjlove Is it an unrelated software that doesn't belong here?

**Comment by jaywcjlove** [comment]
@applecool 
After a number of submissions, can not be merge.

**Comment by jaywcjlove** [comment]
I added manually.

**Comment by applecool** [comment]
@jaywcjlove  Oh I see. So, is there any other way to contribute? Do I contribute to my fork and create a pull request to the repo?

**Comment by jaywcjlove** [comment]
I merge in time. You can contribute. 😄

**Pull request closed without merging**
