### PR TITLE
Deals with item 3 of #330.

### PR DESCRIPTION
**Pull request by alichtman**
Deals with item 3 of https://github.com/jaywcjlove/awesome-mac/issues/330.

### CODE REVIEW

**Comment by jaywcjlove** [comment]
@alichtman thx! My English is very bad.

**Comment by jaywcjlove** [comment]
Thank you for your help.

**Comment by etaletai13** [comment]
@jaywcjlove Talk how you talk, and the native speakers can really understand the spirit of your words. And from there, any can write them. Your difference of language causes a special difference in thought, giving a slight different perspective on all of these things.

**Comment by alichtman** [comment]
Happy to help! I'll keep making improvements and opening PRs over the next few days.

**Comment by jaywcjlove** [comment]
@etaletai13 I am learning and practicing English. This will help me understand more open source projects.

**Comment by jaywcjlove** [comment]
@alichtman I will sync your added content to the Chinese list. thx!

**Pull request merged**
