### PR TITLE
Yunxijun patch 1

### PR DESCRIPTION
**Pull request by yunxijun**
### Types of Changes

- [ ] New addition to list
- [ ] Fixing bug in existing item in list
- [ ] Removing item from list
- [x] Changing structure (organization) of list

### Proposed Changes

1. Just change the link address.

### PR Checklist

- [x] I have read the CONTRIBUTING guide
- [x] I have explained why this PR is important
- [x] I have added necessary documentation (if appropriate)

### Further Comments

- Thanks
- N/A

### CODE REVIEW

**Comment by jaywcjlove** [comment]
#970

**Comment by yunxijun** [comment]
Conficts has dismissed

**Comment by jaywcjlove** [comment]
@yunxijun https://cleanerone.trendmicro.com/unarchiver-one/ Is it not the official website?

**Comment by jaywcjlove** [comment]
@yunxijun The rule is to place the official website, the official website is introduced in more detail, and there may be other application recommendations.

**Comment by yunxijun** [comment]
@jaywcjlove  Ok, thanks for your reply. Then put the previous link on the official website like the first submission, and change the address linked to the appStore to the latest one. I will close this Pull Request and open a new PR to solve the problem.

**Comment by yunxijun** [comment]
@jaywcjlove  Already adjusted.

**Pull request merged**
