### PR TITLE
Add RemoveX

### PR DESCRIPTION
**Pull request by LocNguyenHuu**
NOTE: A similar PR may already be submitted! Please search among the Pull request before creating one.

### Types of Changes

**What types of changes does your PR introduce?** Put an x in all boxes that apply

- [x] New addition to list
- [ ] Fixing bug in existing item in list
- [ ] Removing item from list
- [ ] Changing structure (organization) of list

### Proposed Changes

**Describe each of your changes here to communicate to the maintainers why we should accept this pull request.**

[RemoveX](https://removex.io) - is an uninstaller tool for Mac computer. RemoveX has a beautifully UI using native design for MacOS.

We build RemoveX with a simple way to think, a simple way to use it and really focus on user requirements - uninstall an application as fast as possible.

User will not waste their money on features they do not need, do not understand, sometimes it is useless and rarely to use any more when making a comparison with other complex app.

### PR Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.

- [x] I have read the CONTRIBUTING guide
- [x] I have explained why this PR is important
- [x] I have added necessary documentation (if appropriate)

### Further Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jaywcjlove** [comment]
image

You can add to the Chinese list, your website can only be opened in China. @LocNguyenHuu

**Comment by LocNguyenHuu** [comment]
Dear @jaywcjlove ,

Did you use VPN is it correct? 

Please turn off VPN or any proxy tool and try again because I turn on WAF so it will block all traffics with anonymous IP to protect my site.

My domain is still working now. Thank you for your time.

image

**Comment by LocNguyenHuu** [comment]
Dear @jaywcjlove ,

Please help me to check again. Hope it's working for you because WAF will detect anonymous IP and will response as 403 status code to client (4XX is error at client site, not server site).

Thank you for your time sir.

**Comment by LocNguyenHuu** [comment]
Dear @jaywcjlove ,

I turn off WAF for anonumous IP detect right now, so you can verify again.

Thanks in advance

**Comment by jaywcjlove** [comment]
@LocNguyenHuu The site is now working properly.

**Pull request merged**
