### PR TITLE
Add nushell

### PR DESCRIPTION
**Pull request by omuomugin**
NOTE: A similar PR may already be submitted! Please search among the Pull request before creating one.

### Types of Changes

**What types of changes does your PR introduce?** Put an x in all boxes that apply

- [x] New addition to list
- [ ] Fixing bug in existing item in list
- [ ] Removing item from list
- [ ] Changing structure (organization) of list

### Proposed Changes

**Describe each of your changes here to communicate to the maintainers why we should accept this pull request.**

1. If you're adding something to the list, be sure to explain why it should be added.

nushell is modern shell with unique philosophy. 
It is pipe based and it is well implemented with Rust.

I think it should be on the list. Just take a look if not have seen yet.
https://github.com/nushell/nushell

### PR Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.

- [x] I have read the CONTRIBUTING guide
- [x] I have explained why this PR is important
- [x] I have added necessary documentation (if appropriate)

### Further Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jaywcjlove** [comment]
@omuomugin Can not be installed directly through brew. I don't know how to install `cargo`.

**Comment by omuomugin** [comment]
@jaywcjlove 
Thanks for your response

`Cargo`  is package management tool for Rust and it is installed via rustup
https://doc.rust-lang.org/cargo/getting-started/installation.html

```
curl https://sh.rustup.rs -sSf | sh
```

After that nushell should be installed with nightly cargo, so just run 

```
rustup toolchain install nightly
cargo +nightly install nu
``` 

and your are ready to use

```
nu
```

and you can start the shell.

**Comment by alichtman** [comment]
Use alphabetical order please.

**Comment by omuomugin** [comment]
@alichtman 
Added to the right position.
Should I rebase this into a single commit? or we don't need that?

**Comment by alichtman** [comment]
I squashed the commits so we’re all good.

**Pull request merged**
